/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.2 */
package analyzer.ast;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTAssignStmt node, Object data);
  public Object visit(ASTFunctionStmt node, Object data);
  public Object visit(ASTReturnStmt node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTRealValue node, Object data);
  public Object visit(ASTWhileStmt node, Object data);
  public Object visit(ASTDoWhileStmt node, Object data);
  public Object visit(ASTIfStmt node, Object data);
  public Object visit(ASTForStmt node, Object data);
  public Object visit(ASTParentheses node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTMulti node, Object data);
  public Object visit(ASTDivision node, Object data);
  public Object visit(ASTAddition node, Object data);
  public Object visit(ASTSoustraction node, Object data);
  public Object visit(ASTCompare node, Object data);
  public Object visit(ASTLogic node, Object data);
}
/* JavaCC - OriginalChecksum=9514c0aae3239901d0b2f74f74102d9b (do not edit this line) */
