/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNSTMT = 2;
  public int JJTFUNCTIONSTMT = 3;
  public int JJTRETURNSTMT = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTVALUE = 6;
  public int JJTREALVALUE = 7;
  public int JJTWHILESTMT = 8;
  public int JJTWHILECOND = 9;
  public int JJTWHILEBLOCK = 10;
  public int JJTDOWHILESTMT = 11;
  public int JJTIFSTMT = 12;
  public int JJTIFCOND = 13;
  public int JJTIFBLOCK = 14;
  public int JJTELSEBLOCK = 15;
  public int JJTFORSTMT = 16;
  public int JJTPARENTHESES = 17;
  public int JJTNOT = 18;
  public int JJTMINUS = 19;
  public int JJTMULTI = 20;
  public int JJTDIVISION = 21;
  public int JJTADDITION = 22;
  public int JJTSOUSTRACTION = 23;
  public int JJTCOMPARE = 24;
  public int JJTLOGIC = 25;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "AssignStmt",
    "FunctionStmt",
    "ReturnStmt",
    "Identifier",
    "IntValue",
    "RealValue",
    "WhileStmt",
    "WhileCond",
    "WhileBlock",
    "DoWhileStmt",
    "IfStmt",
    "IfCond",
    "IfBlock",
    "ElseBlock",
    "ForStmt",
    "Parentheses",
    "Not",
    "Minus",
    "Multi",
    "Division",
    "Addition",
    "Soustraction",
    "Compare",
    "Logic",
  };
}
/* JavaCC - OriginalChecksum=7d7a274f7a1c4f8c8024eb9f6f338ded (do not edit this line) */
