/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNSTMT = 2;
  public int JJTFUNCTIONSTMT = 3;
  public int JJTRETURNSTMT = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTVALUE = 6;
  public int JJTREALVALUE = 7;
  public int JJTWHILESTMT = 8;
  public int JJTDOWHILESTMT = 9;
  public int JJTIFSTMT = 10;
  public int JJTFORSTMT = 11;
  public int JJTPARENTHESES = 12;
  public int JJTNOT = 13;
  public int JJTMINUS = 14;
  public int JJTMULTI = 15;
  public int JJTDIVISION = 16;
  public int JJTADDITION = 17;
  public int JJTSOUSTRACTION = 18;
  public int JJTCOMPARE = 19;
  public int JJTLOGIC = 20;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "AssignStmt",
    "FunctionStmt",
    "ReturnStmt",
    "Identifier",
    "IntValue",
    "RealValue",
    "WhileStmt",
    "DoWhileStmt",
    "IfStmt",
    "ForStmt",
    "Parentheses",
    "Not",
    "Minus",
    "Multi",
    "Division",
    "Addition",
    "Soustraction",
    "Compare",
    "Logic",
  };
}
/* JavaCC - OriginalChecksum=4eae49253ada58af16506d82fbbf4c33 (do not edit this line) */
