/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.2 */
package analyzer.ast;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTAssignStmt node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTRealValue node, Object data);
  public Object visit(ASTWhileStmt node, Object data);
  public Object visit(ASTWhileCond node, Object data);
  public Object visit(ASTDoWhileStmt node, Object data);
  public Object visit(ASTIfStmt node, Object data);
  public Object visit(ASTForStmt node, Object data);
  public Object visit(ASTParentheses node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTMulti node, Object data);
  public Object visit(ASTDivision node, Object data);
  public Object visit(ASTAddition node, Object data);
  public Object visit(ASTSoustraction node, Object data);
  public Object visit(ASTCompare node, Object data);
  public Object visit(ASTLogic node, Object data);
}
/* JavaCC - OriginalChecksum=44e909455845d89be601cf279ecd65ae (do not edit this line) */
